spring:
  application:
    name: eureka-server

server:
  port: 9010


eureka:
  instance:
    #设置当前实例的主机名称
    #hostname: ${spring.cloud.client.ipAddress}
    #路径
    prefer-ip-address: true
    #显示的Id
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    #关闭本身的服务注册
    register-with-eureka: false
    #检索服务
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka
  ##关闭保护模式
  server:
    enableSelfPreservation: false