spring:
  application:
    name: admin-client

    #注册监控端
  boot:
    admin:
      client:
        url: http://localhost:9092
        username: user
        password: password


   #开放所有监控端点
    #开启监控
server:
  port: 9091
management:
  endpoints:

    web:
      exposure:
      #开启所有节点
        include: "*"
        #忽略节点
        exclude: [env,beans]
