spring:
  application:
    name: admin-client

    #注册监控端
  boot:
    admin:
      client:
        url: http://localhost:9092

   #开放所有监控端点
    #开启监控
server:
  port: 9091
management:
  endpoints:
    web:
      exposure:
        exclude: "*"

